[build-system]
requires = ["sphinx-rtd-dark-mode"]
# build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Graziella", email = "graziella@lumache"}]
dynamic = ["version", "description"]
